apiVersion: v1
kind: Service
metadata:
  name: jaipro-resource-server
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    service: jaipro-resource-server
    type: backend