spring:
  profiles:
    active: dev
  # R2DBC Driver config
  r2dbc:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PWD}
    pool:
      initial-size: 10
      max-idle-time: 30m

eureka:
  services:
    eureka-clients:
      keycloak-auth:
        url: http://localhost:8090/eureka/keycloak-auth/v1
        readTimeout: 7000
        writeTimeout: 1000
        connectionTimeout: 300
      resource-server:
        url: http://localhost:8090/eureka/resource-server/v1
        readTimeout: 7000
        writeTimeout: 1000
        connectionTimeout: 300

